ALTER TABLE public.community_posts
  ADD COLUMN IF NOT EXISTS font_size text NOT NULL DEFAULT 'base',
  ADD COLUMN IF NOT EXISTS line_height text NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS text_color text NOT NULL DEFAULT '#61777d';

DO $$ BEGIN
  ALTER TABLE public.community_posts ADD CONSTRAINT community_posts_font_size_check CHECK (font_size IN ('sm','base','lg','xl'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.community_posts ADD CONSTRAINT community_posts_line_height_check CHECK (line_height IN ('compact','normal','relaxed','loose'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.community_posts ADD CONSTRAINT community_posts_text_color_check CHECK (text_color ~ '^#[0-9A-Fa-f]{6}$');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.community_post_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,
  image_url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS community_post_images_post_sort_idx ON public.community_post_images(post_id, sort_order, id);
ALTER TABLE public.community_post_images ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.community_post_images FROM anon, authenticated;
DROP POLICY IF EXISTS deny_direct_post_image_access ON public.community_post_images;
CREATE POLICY deny_direct_post_image_access ON public.community_post_images FOR ALL USING (false) WITH CHECK (false);

INSERT INTO public.community_post_images(post_id,image_url,sort_order)
SELECT p.id,p.image_url,0 FROM public.community_posts p
WHERE p.image_url IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM public.community_post_images i WHERE i.post_id=p.id);

INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES ('site-media','site-media',false,104857600,ARRAY['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime'])
ON CONFLICT (id) DO UPDATE SET public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
