export type SiteContent = Record<string, string>;

export const DEFAULT_SITE_CONTENT: SiteContent = {
  brandName: "伴宠",
  brandAccent: "公益",
  navHome: "首页",
  navCommunity: "救助社区",
  navActivities: "公益活动",
  navAbout: "About",
  navLogin: "登录",
  navRegister: "免费注册",
  navPublish: "发布动态",
  navAdmin: "管理后台",

  heroEnabled: "true",
  heroBadge: "让善意被看见，也被延续",
  heroTitleLine1: "让每个生命",
  heroTitleAccent: "都有回家的路",
  heroDescription: "连接救助人、志愿者与领养家庭。分享真实救助故事，组织身边的公益行动，一起把微小善意变成长期改变。",
  heroPrimaryButton: "发布救助动态",
  heroSecondaryButton: "参加公益活动",
  stat1Value: "12,860",
  stat1Label: "爱心会员",
  stat2Value: "3,204",
  stat2Label: "成功救助",
  stat3Value: "186",
  stat3Label: "城市伙伴",

  videoEnabled: "true",
  videoUrl: "https://www.youtube.com/embed/ObXjfWx-1vI",
  videoLabel: "本周救助纪录",
  videoTitle: "每一次伸手，都可能改变一个生命",
  trustTitle: "真实救助认证",
  trustSubtitle: "让每份爱心更安心",

  communityEnabled: "true",
  communityEyebrow: "COMMUNITY",
  communityTitle: "正在发生的温暖故事",
  communityDescription: "记录救助进展、领养日常和那些值得被看见的瞬间。",
  communityPublishButton: "我也要发布",

  featuredPost1Author: "城市流浪动物志愿队",
  featuredPost1Title: "小满终于找到愿意等它慢慢靠近的人",
  featuredPost1Content: "从怕人躲在角落，到第一次把爪子交给新家人，87天的等待都有了答案。",
  featuredPost1Image: "https://images.squarespace-cdn.com/content/v1/63602a7497377c44ecf43dcb/df633d5f-c7f8-466c-990f-d1136e81c373/IMG-4553.jpg?format=1500w",
  featuredPost1Category: "领养故事",
  featuredPost1Time: "今天",
  featuredPost2Author: "阿橘的临时妈妈",
  featuredPost2Title: "第一次做猫咪中途，我准备了这些",
  featuredPost2Content: "隔离、体检、驱虫和适应期记录，希望这份清单也能帮到第一次参与救助的你。",
  featuredPost2Image: "https://images.squarespace-cdn.com/content/v1/565cbc71e4b0b80773b05964/3030a0ac-bbad-430e-af5f-243f6bea3c10/2.%2BLotus%2Bin%2BCat%2BRoom.jpg?format=2500w",
  featuredPost2Category: "救助经验",
  featuredPost2Time: "2小时前",
  featuredPost3Author: "周末遛狗小分队",
  featuredPost3Title: "我们给救助站的孩子过了一个草地下午",
  featuredPost3Content: "12位志愿者、18只狗狗，阳光和耐心让每一次牵绳都变成新的信任。",
  featuredPost3Image: "https://images.squarespace-cdn.com/content/v1/6320d54457f5be71975cead0/1681134994755-MMDK4Q7XGUZT9ZP5P2LN/4%2BARL.jpg?format=500w",
  featuredPost3Category: "活动现场",
  featuredPost3Time: "昨天",

  activitiesEnabled: "true",
  activitiesEyebrow: "ACTIVITIES",
  activitiesTitle: "把“想帮忙”变成一次行动",
  activitiesDescription: "发起或参加身边的清洁、陪伴、领养和科普活动，认识同样在乎生命的人。",
  activitiesCreateButton: "发起活动",
  activitiesJoinButton: "立即报名",

  featuredActivity1Organizer: "伴宠志愿者联盟",
  featuredActivity1Title: "周末救助站清洁与陪伴",
  featuredActivity1Description: "一起清洁犬舍、补充物资，也给等待领养的孩子一段高质量陪伴。",
  featuredActivity1Location: "上海 · 浦东新区",
  featuredActivity1Date: "2026-09-06T09:30",
  featuredActivity1Capacity: "24",
  featuredActivity1Members: "16",
  featuredActivity2Organizer: "社区萌宠守护组",
  featuredActivity2Title: "流浪猫科学救助分享会",
  featuredActivity2Description: "兽医与长期救助人现场分享TNR、应急处置和邻里沟通经验。",
  featuredActivity2Location: "深圳 · 南山区",
  featuredActivity2Date: "2026-09-12T14:00",
  featuredActivity2Capacity: "60",
  featuredActivity2Members: "41",
  featuredActivity3Organizer: "城市领养日",
  featuredActivity3Title: "秋日公益领养见面会",
  featuredActivity3Description: "和经过健康检查的待领养猫狗见面，现场有专业领养评估与养宠咨询。",
  featuredActivity3Location: "杭州 · 拱墅区",
  featuredActivity3Date: "2026-09-20T10:00",
  featuredActivity3Capacity: "100",
  featuredActivity3Members: "73",

  aboutEnabled: "true",
  aboutEyebrow: "ABOUT US",
  aboutTitle: "我们相信，公益不只是捐款，更是每个人都能参与的日常。",
  aboutDescription: "伴宠公益是一个围绕宠物救助、领养与生命教育的社区平台。我们希望用可信的信息、真实的记录和便捷的活动组织，让分散的善意更容易汇聚。",
  aboutMetricValue: "100%",
  aboutMetricLabel: "专注宠物公益赛道",
  aboutTogetherValue: "一起",
  aboutTogetherLabel: "让救助不再是孤军奋战",
  aboutPoint1: "真实透明的救助记录",
  aboutPoint2: "尊重生命的领养理念",
  aboutPoint3: "在地化志愿者协作",
  aboutPoint4: "长期可持续的公益连接",

  ctaEnabled: "true",
  ctaTitle: "从今天开始，成为它们的同行者",
  ctaDescription: "加入社区，分享一条信息、参加一次活动，也许就能帮一个生命找到转机。",
  ctaGuestButton: "免费注册会员",
  ctaMemberButton: "去发布第一条动态",
  footerText: "© 2026 伴宠公益 · 尊重生命，理性救助，以领养代替购买",
};

export function mergeSiteContent(rows: Array<{ key: string; value: string }>): SiteContent {
  return { ...DEFAULT_SITE_CONTENT, ...Object.fromEntries(rows.map((row) => [row.key, row.value])) };
}

export function isKnownContentKey(key: string) {
  return Object.prototype.hasOwnProperty.call(DEFAULT_SITE_CONTENT, key);
}
